apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-app-r10
  namespace: default
  labels:
    app: test-app-r10
spec:
  replicas: 1
  selector:
    matchLabels:
      app: test-app-r10
  template:
    metadata:
      labels:
        app: test-app-r10
    spec:
      containers:
      - name: test-app-r10
        image: localhost/test-app-r10:1.0.0
        ports:
        - containerPort: 5211
---
apiVersion: v1
kind: Service
metadata:
  name: test-app-r10
  namespace: default
spec:
  selector:
    app: test-app-r10
  ports:
    - protocol: TCP
      port: 5211
      targetPort: 5211
---